README.md

Show code coverage badge in README.

docs: add code coverage badge to README

---

docs/installation.md

Add instructions how to start the wfx container image.

docs: add container setup instructions

---

.goreleaser.yml

Consistent naming of generated artifacts. In particular, use x86_64 instead of amd64 to avoid confusion with arm64 as they look alike.

Adjust goreleaser setup

---

README.md
workflow/dau/README.md

[SWUpdate](https://github.com/sbabic/swupdate) has merged the wfx support patches, hence update documentation.

docs: update SWUpdate linking for merged wfx patches

---

hugo/content/_index.html
hugo/package-lock.json
hugo/package.json

In response to the logo cropping in commit e730b07b, this update adjusts the whitespace between the logo and neighboring text on the documentation landing page.

Adjust whitespace for improved logo and text separation

---

.github/dependabot.yml

This commit enables Dependabot to check for updates of Golang dependencies on a monthly basis, thereby enhancing security and compatibility.

ci: add dependabot support for Golang dependencies

---

.goreleaser.yml

This commit modifies the CI pipeline to create new releases in draft mode. This offers an additional layer of control, allowing for a final manual review prior to publishing the release.

ci: implement draft mode for new releases

---

workflow/dau/README.md

- add workflow installation instructions
- update example job definition for easy copy-pasting

docs: enhance DAU documentation

---

api/northbound_test.go
api/southbound_test.go
cmd/wfx/cmd/root/cmd.go
cmd/wfx/cmd/root/northbound.go
cmd/wfx/cmd/root/southbound.go
generated/northbound/restapi/configure_workflow_executor.go
generated/southbound/restapi/configure_workflow_executor.go
internal/config/koanf.go
internal/producer/json.go
internal/producer/json_test.go

This contains minor refactorings and preparations for #11. To make the review of the latter easier, I have put all refactorings in this merge request.

Minor refactorings

---

.ci/setup/swagger.sh
generated/model/error_response.go
generated/model/history.go
generated/model/job.go
generated/model/paginated_job_list.go
generated/model/paginated_workflow_list.go
generated/model/transition.go
generated/model/workflow.go
generated/northbound/restapi/operations/workflow_executor_api.go
generated/southbound/restapi/operations/workflow_executor_api.go

Contains some bug fixes, see https://github.com/go-swagger/go-swagger/releases/tag/v0.30.5

chore: update go-swagger 0.30.4 -> 0.30.5

---

cmd/wfxctl/cmd/workflow/validate/validate.go
go.mod
shell.nix

- Replaced instances of yaml.v2
- Adopted yaml.v3 consistently to simplify maintenance and ensure consistent (parsing) behavior

chore: Unify YAML parsing with yaml.v3 throughout the project

---

CHANGELOG.md
generated/ent/migrate/schema.go
generated/ent/mutation.go
generated/ent/runtime.go
generated/ent/schema/workflow.go
generated/ent/workflow.go
generated/ent/workflow/where.go
generated/ent/workflow/workflow.go
generated/ent/workflow_create.go
generated/ent/workflow_update.go
generated/model/workflow.go
generated/northbound/restapi/embedded_spec.go
generated/southbound/restapi/embedded_spec.go
internal/persistence/entgo/migrations/mysql/20231026152159_add-workflow-description.down.sql
internal/persistence/entgo/migrations/mysql/20231026152159_add-workflow-description.up.sql
internal/persistence/entgo/migrations/mysql/atlas.sum
internal/persistence/entgo/migrations/postgres/20231026152156_add-workflow-description.down.sql
internal/persistence/entgo/migrations/postgres/20231026152156_add-workflow-description.up.sql
internal/persistence/entgo/migrations/postgres/atlas.sum
internal/persistence/entgo/migrations/sqlite/20231026152143_add-workflow-description.down.sql
internal/persistence/entgo/migrations/sqlite/20231026152143_add-workflow-description.up.sql
internal/persistence/entgo/migrations/sqlite/atlas.sum
internal/persistence/entgo/workflow_create.go
internal/persistence/entgo/workflow_get.go
spec/wfx.swagger.yml
workflow/dau/wfx.workflow.dau.direct.yml
workflow/dau/wfx.workflow.dau.phased.yml

This commit introduces a top-level 'description' field to workflows, allowing users to provide extra documentation or context.

feat: add optional 'description' field to workflows

---

internal/producer/json.go
internal/producer/json_test.go

Insights from code coverage indicated that `internal/producer` had a suboptimal test coverage of 58%. This shortfall was primarily due to untested error conditions. As it turns out, some of these error conditions are in fact impossible.
Changes made:
1. Added tests for previously uncovered failure scenarios.
2. Removed redundant error checks for scenarios we can guarantee won't occur such as unmarshaling errors when input validity is already confirmed.

test: increase test coverage for internal/producer

---

middleware/fileserver/fileserver.go

Log the directory which is exposed by the internal file server for the user's convenience.

chore: log fileserver directory if enabled

---

.github/dependabot.yml

chore(dependabot): manage Hugo's Go dependencies

---

README.md
contrib/config-deployment/README.md
docs/use-cases.md
hugo/.gitignore
hugo/Makefile
hugo/config.toml
hugo/filters/fix-links-post.lua
hugo/filters/fix-links-pre.lua

This adds the two PoCs from #79 as use-cases to the documentation. So the actual file to review is [docs/use-cases.md](https://github.com/siemens/wfx/pull/84/files#diff-28b4aebcc35109108a694ac87deaab84e6006509322fe636d1306452081d140e), the rest is just fixes and code to make the documentation links work properly.

 Add use-cases to documentation

---

.github/workflows/ci.yml
.gitignore
CHANGELOG.md
middleware/plugin/fbplugin.go
middleware/plugin/process_unix.go
middleware/plugin/process_windows.go

fix(build): support for Windows

---

.goreleaser.yml

This removes the `+git` version suffix from our released `*.deb` packages (as can be seen by inspecting it via `dpkg -I`) and chooses more appropriate sections.

chore: remove +git version suffix, update Debian sections

---

.github/workflows/ci.yml
.github/workflows/release.yml
shell.nix

Finally we can upgrade Zig (our C cross-compiler). See https://github.com/ziglang/zig/issues/15610.

chore: update to Zig 0.12.0

---

CHANGELOG.md

chore: add release v0.3.0 to changelog

---

.goreleaser.yml
CHANGELOG.md

Zstd offers faster compression and decompression speeds while providing similar compression ratios.

feat: switch release tarball compression to zstd from xz

---

.goreleaser.yml

Otherwise goreleaser issues a warning during build.

chore: add version field to goreleaser config

---

renovate.json5

Otherwise, if the depType is a known "production dependency" type (e.g. dependencies or require), then Renovate would use the "fix" prefix.

ci(renovate): use the "chore" type for every PR

---

.ci/packages/syft.sh
.ci/packages/versions.env
.ci/setup-build.sh
.goreleaser.yml
shell.nix

Enhance transparency and security by providing a Software Bill of Materials (SBOM) for release artifacts, enabling easier tracking and auditing of dependencies.

ci: generate SBOMs for release artifacts using goreleaser

---

.ci/check-links.py
.github/workflows/pages.yml
justfile
lychee.toml

- Ignore certain sites (e.g. mysql) which are known not to work with the link check
- Lower severity of broken links from warning to error

ci: improve link check

---

.github/workflows/pages.yml

Fixes issue where pages were not being built after merging to the main branch.

ci: ensure pages build on push and workflow_dispatch

---

CHANGELOG.md
cmd/wfx/cmd/config/flags.go
cmd/wfx/cmd/root/root.go
cmd/wfx/cmd/root/tag_mysql.go
cmd/wfx/cmd/root/tag_plugin.go
cmd/wfx/cmd/root/tag_postgres.go
cmd/wfx/cmd/root/tag_sqlite.go

Simplify inspection of a deployed wfx binary by including additional build context at a glance.

feat: add build tags to --version output

---

cmd/wfx/cmd/root/server_collection_test.go
generated/api/wfx.openapi.gen.go
spec/openapiv3.go
spec/wfx.openapiv3.yml

Implemented RFC 8631's `service-desc` Link Relation Type to make the OpenAPI v3 specification auto-discoverable.
Named operations more CLI friendly using the `x-cli-name` and `x-cli-hidden` extension tags to make wfx's OpenAPI v3 specification more accessible and reword some descriptions to the same end.

Make OpenAPI v3 specification more CLI-accessible

---

README.md

Fixes a broken CI badge in our `README.md`

docs: fix broken link to recently removed CI job

---

cmd/wfx/cmd/config/flags.go
cmd/wfx/cmd/root/setup.go

Pass structured log data to journald using its native protocol [1].
[1] https://systemd.io/JOURNAL_NATIVE_PROTOCOL/

feat: add journald-friendly log format

---

.ci/setup-mysql.sh
.ci/setup-postgres.sh
.github/workflows/ci.yml
.gitlab-ci.yml
justfile

Add postgres and mysql tests to coverage

ci: add postgres and mysql tests to coverage

---

.goreleaser.yml
docs/installation.md

- Add documentation for `no_swagger` build tag
- Run `just format` to format docs and yaml files

Document no_swagger build tag

---

.goreleaser.yml

- Add "Features (breaking)" group for breaking changes
- Refine regex for features and bug fixes
- Exclude `chore`, `ci`, `docs`, and `test` commits

chore(goreleaser): improve changelog grouping

---

renovate.json5

Don't remove whitespace between the version and the comment (#) marker.

ci: fix renovate regex
