.golangci.yml
cmd/wfxctl/errutil/util.go

Correct the spelling of "occurred" from its incorrect form "occured". Integrate a spell-check linter into the build process to automatically identify and prevent spelling mistakes in the future.

style: correct spelling and enforce linter check

---

CHANGELOG.md
middleware/fileserver/fileserver.go
middleware/fileserver/fileserver_test.go

Send HTTP status code 404 when attempting to access the file server while it is disabled.

 fix: send HTTP code 404 if file server disabled

---

docs/configuration.md
docs/workflows.md

Currently, there exists a mixture of "you" and passive voice in the documentation, leading to an inconsistent writing style. This commit addresses the issue by replacing all instances of "you" with passive voice, ensuring a consistent and cohesive writing style across the entire documentation.

docs: replace "you" with passive voice

---

.github/workflows/ci.yml
.golangci.yml
CHANGELOG.md
cmd/wfx/cmd/root/cmd.go
cmd/wfx/cmd/root/northbound.go
cmd/wfx/cmd/root/server.go
cmd/wfx/cmd/root/server_test.go
cmd/wfx/cmd/root/southbound.go
cmd/wfx/cmd/root/systemd.go
internal/server/http.go
test/02-configuration.bats
test/04-operations.bats
test/Makefile

It was observed that the TLS configuration was omitted for the Southbound API. Although there is a test case to validate this configuration, it was previously executed manually, which led to it being inadvertently neglected on a regular basis. To address this, the present merge request not only includes the requisite changes for configuring TLS for the Southbound API but also automates the execution of the CLI tests within the Continuous Integration (CI) pipeline.

Configure TLS for Southbound API

---

share/demo/kanban/02-create-workflow.sh
share/demo/kanban/03-producer.sh

This commit addresses an issue where the producer in the Kanban demo would halt after generating a certain number of jobs. Earlier, even if the producer was restarted, it wouldn’t resume the job generation due to the presence of a '.done' marker file.
The marker file mechanism was therefore replaced with a simple polling approach. Now restarting the producer works and will result in new jobs being generated.

fix(demo): run kanban demo in an infinite loop

---

CHANGELOG.md
api/main_test.go
api/workflow_test.go
go.mod
go.sum
internal/handler/job/create_test.go
internal/handler/job/definition/get_test.go
internal/handler/job/definition/main_test.go
internal/handler/job/main_test.go
internal/handler/job/status/get_test.go
internal/handler/job/status/main_test.go
internal/handler/job/tags/add_test.go
internal/handler/job/tags/main_test.go
internal/handler/workflow/create_test.go
internal/handler/workflow/main_test.go
internal/persistence/entgo/main_test.go
internal/persistence/entgo/mysql.go
internal/persistence/entgo/mysql_test.go
internal/persistence/entgo/postgres_test.go
internal/persistence/entgo/sqlite.go
internal/persistence/entgo/sqlite_test.go
shell.nix

Previously, a separate connection pool was created to execute schema migrations. This pool was not properly shut down though, leading to open connections and unused goroutines. This commit reuses the connection pool created for entgo, thereby preventing any resource leaks.

fix(persistence): connection pool leak due to schema migrations

---

test/04-operations.bats

Updated the teardown process to halt wfx after every test. This addresses issues where subsequent tests couldn't bind to certain ports due to lingering wfx instances.

test: ensure wfx shutdown after each test run

---

.github/workflows/ci.yml
.golangci.yml
.goreleaser.yml
docs/installation.md
go.mod
internal/persistence/entgo/sqlite_test.go
middleware/fileserver/fileserver_test.go
middleware/logging/writer_test.go

- ioutil is deprecated in Go 1.19, see https://pkg.go.dev/io/ioutil@go1.19
- require at least Go 1.19 (1.18 is end-of-life)
- goreleaser rlcp is now the default and can't be changed

Fix deprecations

---

justfile

Currently everything except for the `ent` directory is removed. This does not scale when adding more generated code. Instead, the swagger task should only purge its own files (before recreating them).

ci: restrict swagger code purging to own files

---

.golangci.yml
api/northbound.go
api/northbound_test.go
api/southbound.go
api/southbound_test.go
api/workflow_test.go
cmd/wfx/cmd/root/cmd.go
cmd/wfx/cmd/root/cmd_test.go
cmd/wfx/cmd/root/northbound.go
cmd/wfx/cmd/root/server.go
cmd/wfx/cmd/root/southbound.go
codecov.yml
internal/errutil/main_test.go
internal/errutil/wrap.go
internal/errutil/wrap_test.go

wfx now promptly shuts down upon receiving signals, such as CTRL-C. Previously, it might enter a loop if its listening port was unavailable, rendering it unresponsive to signals during that period.

fix: ensure immediate shutdown on signals

---

cmd/wfxctl/cmd/job/query/query.go
test/05-workflows.bats

Fix wfxctl --group filtering option so it correctly accepts a list of group names.
Currently the group filter is ignored because of the wrong type of the argument.
Add bash CLI tests for wfxctl --group option.

fix: filter wfxctl job query by group

---

.github/workflows/pages.yml
.markdown-link-check.json
docs/configuration.md

Ensure we run the markdown link checker as part of our CI pipeline. It complains about a broken link (case-sensitive) but luckily this is not an issue in practice (although it's correct to use a lowercase link).

ci: check for broken links

---

CHANGELOG.md
api/northbound.go
cmd/wfxctl/cmd/workflow/delete/delete.go
cmd/wfxctl/cmd/workflow/delete/delete_test.go

- Change `wfxctl workflow delete` to take workflows as arguments rather than positional parameters
- Return a descriptive error message along with a 404 status code if the specified workflow is not found

refactor!: `wfxctl workflow delete` to accept workflows as arguments

---

internal/handler/workflow/get.go
internal/handler/workflow/get_test.go

Logging errors should be reserved for situations warranting further investigation, such as issues with the persistent storage. A query for a (not yet) existing workflow is not an exceptional case and should not trigger error logging. This commit removes the unnecessary logging of such events.

style: suppress error logging for non-existent workflows

---

CHANGELOG.md
cmd/wfx/main.go
go.mod
go.sum

The GOMAXPROCS variable limits the number of operating system threads that can execute user-level Go code simultaneously. This commit adjusts how GOMAXPROCS is determined by preferring the CPU quota defined in cgroups, which provides a more accurate representation of available CPUs for environments like Kubernetes, where the assigned CPU resources may be lower than the actual CPU count. This ensures fair resource distribution and avoids over-allocation. If cgroup information is unavailable, the default remains the host CPU count.

feat: prefer cgroup CPU quota over host CPU count

---

justfile

The current "latest is greatest" approach breaks our CI pipelines forcing us to upgrade entgo as soon as a new version has been released. We use dependabot to keep our dependencies updated though.

ci: pin entgo version for stable codegen

---

CHANGELOG.md
cmd/wfx/cmd/root/cmd.go
cmd/wfx/main.go

Log messages from automaxprocs/maxprocs are now seamlessly integrated into our existing logging framework.
Previously, automaxprocs/maxprocs relied solely on `printf` for outputting messages directly to stdout. This approach bypassed any user-defined log levels, leading to potential issues in log verbosity and management.

chore: integrate automaxprocs/maxprocs with zerolog

---

CHANGELOG.md
internal/handler/job/create_test.go
internal/persistence/entgo/job_create.go

When querying one or multiple jobs, the response always includes the workflow definition. However, this was not the case when creating a new job; the response omitted the workflow definition. This inconsistency not only diverged from our established response behavior but also from the examples generated in our Swagger documentation. This change ensures that the response for newly created jobs includes the workflow definition, aligning it with our existing standards and documentation.

fix: include workflow definition in response when creating jobs

---

docs/workflows.md
generated/model/job.go
generated/northbound/restapi/embedded_spec.go
generated/southbound/restapi/embedded_spec.go
spec/wfx.swagger.yml

The purpose of this merge request is to clarify when the job history is included in responses.

docs: clarify when the job history is included in responses

---

Makefile

Use the invoking `make` for make calls in Makefile, see https://www.gnu.org/software/make/manual/html_node/MAKE-Variable.html
This fixes compilation on BSDs where GNU make is usually installed as `gmake`.

fix(Makefile): Use invoking make in Makefile's make calls

---

CHANGELOG.md
cmd/wfxctl/errutil/util.go
middleware/logging/log.go
middleware/logging/writer.go
middleware/logging/writer_test.go
middleware/plugin/middleware.go

Details:
- Altered the log level for certain plugin messages from INFO to DEBUG to reduce overall verbosity.
- Implemented logging of HTTP response codes at INFO level. This improves diagnostics, as HTTP status codes were not previously logged at all.
- Fixed an issue with logging the response body for non-JSON plugin log messages. Previously, the response body was assumed to be valid JSON, which may not always be the case for plugins.

feat: enhance logging with HTTP status code, adjust and fix some log messages

---

codecov.yml

This commit excludes both the loadtest and viewer modules from coverage data collected by codecov. A recent change in Codecov's behavior has unexpectedly included these modules in coverage tracking. While there may be an opportunity to implement tests for wfx-viewer in the future, the primary objective of this commit is to revert the code coverage metrics to their original state.

ci: exclude loadtest and viewer from code coverage

---

.github/workflows/pages.yml

This commit addresses a critical issue where Hugo versions between 0.123.0 and 0.123.6 generate incorrect integrity hashes for static assets (such as JavaScript files).
The workaround is to pin Hugo's version to a previously stable version that does not exhibit this problem.

fix: asset integrity hash generation in hugo

---

.github/workflows/pages.yml

Pin markdown-link-check to version 3.11.2 until https://github.com/tcort/markdown-link-check/issues/304 is resolved in the 3.12.x series.
Current markdown link check fails due to a regression in 3.12.x

chore(deps): pin markdown-link-check@3.11.2

---

.github/workflows/chore.yml

Renovatebot currently lacks the capability to run 'go mod tidy', so we need to automate this process ourselves. This prevents the go.sum file from growing indefinitely.

ci: automate running 'go mod tidy'

---

CHANGELOG.md
cmd/wfx/cmd/root/plugins.go
cmd/wfx/cmd/root/plugins_disabled.go
cmd/wfx/cmd/root/plugins_disabled_test.go
cmd/wfx/cmd/root/plugins_enabled.go

wfx does not start if built without `plugin` tag

fix: wfx does not start if built without plugin tag

---

.goreleaser.yml

The property snapshot.name_template has been renamed to snapshot.version_template since goreleaser v2.2, see [1].
[1] https://goreleaser.com/deprecations/#snapshotname_template

ci(goreleaser): fix a deprecation

---

renovate.json5

Updating indirect dependencies in the main go.mod does not make sense as they are not being used and are reverted by running go mod tidy.

ci(renovate): update indirect deps only for hugo

---

codecov.yml

Instead of failing the CI pipeline when code coverage slightly decreases, this change sets the codecov severity to informational. This allows the reviewer to assess the coverage changes and make the decision on whether to accept the changes, rather than automatically failing the build. This provides more flexibility and context for the coverage changes.

ci: lower codecov severity to informational

---

CHANGELOG.md
cmd/wfx/cmd/root/root_test.go
cmd/wfx/cmd/root/server_collection_test.go
docs/operations.md
spec/openapiv3.go

Change OpenAPI v3 spec endpoint from /api/wfx/v1/openapiv3.json to /api/wfx/v1/openapi.json. This change aligns with the convention of using openapi.json as the standard name to serve the OpenAPI spec.

refactor: update OpenAPI spec endpoint path

---

cmd/wfx/cmd/root/plugins_test.go

On macOS, `/var` is symlinked to `/private/var` so that `$TMPDIR` != `$(realpath $TMPDIR)`. Hence, compare
fully qualified and symlink-resolved paths.

test: Fix paths comparison on macOS

---

codecov.yml

Exclude test code from code coverage

test: exclude test code from code coverage

---

.github/workflows/ci.yml

Automatically detect breaking changes in the API by running oasdiff in CI. The build will fail if any breaking changes are detected, ensuring API stability.
Reference: https://github.com/Tufin/oasdiff

ci: integrate oasdiff to detect breaking API changes

---

cmd/wfx/cmd/root/server_collection.go
cmd/wfx/cmd/root/server_collection_test.go

The base middlewares (baseMWs) were not being invoked due to an incorrect use of the copy() function, which only copies elements up to the length of the destination slice. Since the destination slice was initialized with zero length, no elements were copied. This has been fixed by appending each middleware function individually to the combinedMWs slice.
Fixes: f9825d67c1652e2b36cab526d7aa7d9bcd85ce85 (not yet released)

fix: baseMWs are not called

---

CHANGELOG.md
middleware/logging/log.go

Access log level was changed from INFO to DEBUG to avoid logging a message for every poll by each client.
To restore the old behavior, start wfx with --log-level=DEBUG (note that this will enable additional log messages though).
Closes #292 

feat: change access log level to debug

---

CHANGELOG.md
api/job_events_test.go
docs/operations.md
middleware/logging/writer.go
middleware/sse/recorder.go
middleware/sse/responder.go
middleware/sse/responder_test.go

Job event connections were prematurely closed due to inactivity.
Fixes: 976875fab380ef85ece8c3b835a3ae4e891f9e70

fix: do not close SSE connection due to inactivity

---

CHANGELOG.md
api/job_events_test.go
api/wfx.go
api/wfx_test.go
cmd/wfx/cmd/config/appconfig.go
cmd/wfx/cmd/config/flags.go
cmd/wfx/cmd/root/server_collection.go
cmd/wfxctl/cmd/job/events/events.go
cmd/wfxctl/cmd/job/events/events_test.go
cmd/wfxctl/flags/basecmd.go
docs/operations.md
go.mod
go.sum
internal/handler/job/create.go
internal/handler/job/create_test.go
internal/handler/job/definition/update.go
internal/handler/job/definition/update_test.go
internal/handler/job/delete.go
internal/handler/job/delete_test.go
internal/handler/job/events/events.go
internal/handler/job/events/events_test.go
internal/handler/job/status/update.go
internal/handler/job/status/update_test.go
internal/handler/job/tags/add.go
internal/handler/job/tags/add_test.go
internal/handler/job/tags/delete.go
internal/handler/job/tags/delete_test.go
middleware/sse/recorder.go
middleware/sse/responder.go
middleware/sse/responder_test.go

Rewrite subscriber events implementation since upstream seems to be abandoned and buggy.
Reported-by: Felix Moessbauer <felix.moessbauer@siemens.com>

fix: subscriber events deadlock

---

CHANGELOG.md
Dockerfile

This change simplifies container usage. Previously, exposing the `--mgmt-port` required both `--publish` and manually setting `--mgmt-host=0.0.0.0` as a CLI argument to wfx.
Note: The `--mgmt-host` value can still be overridden by passing it as an argument to docker run; the last occurrence takes precedence.

feat(docker): bind --mgmt-host to all interfaces
